# Generated by Django 5.2.6 on 2025-09-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepqualityoption',
            name='quality_label',
            field=models.CharField(max_length=50),
        ),
    ]
