# Generated by Django 5.2.6 on 2025-12-01 23:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_sleepqualityoption_quality_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepqualityoption',
            options={'ordering': ['-score'], 'verbose_name': 'Opción de Calidad de Sueño', 'verbose_name_plural': 'Opciones de Calidad de Sueño'},
        ),
        migrations.AlterModelOptions(
            name='sleepsession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Sesión de Sueño', 'verbose_name_plural': 'Sesiones de Sueño'},
        ),
        migrations.RenameField(
            model_name='sleepsession',
            old_name='recorded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='sleepqualityoption',
            name='score',
            field=models.IntegerField(default=3, help_text='Puntuación numérica de la calidad (1 es muy mala, 5 es excelente).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación (1-5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='sleepqualityoption',
            name='quality_label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Etiqueta de Calidad'),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Calculado a partir de la diferencia entre Inicio y Fin.', null=True, verbose_name='Duración (minutos)'),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='end_time',
            field=models.DateTimeField(verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sleepqualityoption', verbose_name='Calidad del Sueño'),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='sleep_interruptions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interrupciones'),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='sleep_stage_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos de Fases (JSON)'),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='start_time',
            field=models.DateTimeField(verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
    ]
